### PR TITLE
fix(wallet-frontend): sent/received toggle

### LINKED ISSUE #261: Send/Receive Switch functionality
The send/receive switch-toggle functionality on Pay/Send pages needs to be updated to send correct boolean value.
Right now it is sending true every time.

### PR DESCRIPTION
**Pull request by raducristianpopa**
### Context
- fixes #261 

### Changes
Correctly sends `isReceive: true | false` based on the sent/received toggle.

### CODE REVIEW

File: packages/wallet-frontend/src/lib/api/transfers.ts [hunk 1]
```diff
@@ -81,7 +82,13 @@ const createTransfersService = (): TransfersService => ({
     try {
       const response = await httpClient
         .post('outgoing-payments', {
-          json: args
+          json: {
+            accountId: args.accountId,
+            paymentPointerId: args.paymentPointerId,
+            toPaymentPointerUrl: args.toPaymentPointerUrl,
+            amount: args.amount,
+            isReceive: args.paymentType === 'received' ? true : false
```
Comment (Tymmmy) [inline packages/wallet-frontend/src/lib/api/transfers.ts:90]:
```suggestion
            isReceive: args.paymentType === 'received'
```

File: packages/wallet-frontend/src/ui/TogglePayment.tsx [hunk 2]
```diff
@@ -1,24 +1,38 @@
...
 
-export const TogglePayment = ({ type, disabled }: ToggleProps) => {
-  const [enabled, setEnabled] = useState(false)
+// TODO: Look into replacing HeadlessUI with Radix
+export const TogglePayment = ({
+  type,
+  disabled = false,
+  onChange
+}: ToggleProps) => {
+  const value = type === 'sent' ? false : true
```
Comment (Tymmmy) [inline packages/wallet-frontend/src/ui/TogglePayment.tsx:24]:
```suggestion
  const value = type !== 'sent'
```

**Review by Tymmmy — APPROVED** [review]
