### PR TITLE
fix(wallet): Verify image type for KYC upload

### LINKED ISSUE #185: Image validation for KYC
Rapyd only accepts JPEG and PNG images for ID proof. We should have some extra validation to prevent unnecessary calls to Rapyd API.

References: 
- [Rapyd API Docs](https://docs.rapyd.net/build-with-rapyd/reference/identity-verification#identity-verification-errors)
- https://github.com/interledger/testnet/pull/180#discussion_r1132332696

### PR DESCRIPTION
**Pull request by Tymmmy**
### Context
- fixes #185 

### Changes

### CODE REVIEW

File: packages/wallet/src/lib/api/user.ts [hunk 1]
```diff
@@ -38,19 +38,53 @@ export const personalDetailsSchema = z.object({
...
+    if (!ACCEPTED_IMAGE_TYPES.includes(frontSideImageType.toString())) {
+      ctx.addIssue({
+        code: 'custom',
+        message: `Image must be 'jpeg' or 'png'`,
+        path: ['frontSideImage']
+      })
+    }
+  })
+  .superRefine(({ faceImageType }, ctx) => {
+    if (!ACCEPTED_IMAGE_TYPES.includes(faceImageType.toString())) {
```
Comment (raducristianpopa) [inline packages/wallet/src/lib/api/user.ts:66]:
```suggestion
    if (!ACCEPTED_IMAGE_TYPES.includes(faceImageType)) {
```

**Review by raducristianpopa — COMMENTED** [review]
I think we should be able to do all the validations inside a single `superRefine` instead of calling `superRefine` 3 times.

**Review by raducristianpopa — APPROVED** [review]
