### PR TITLE
fix(boutique): add description to payments

### LINKED ISSUE #786: Add description to incoming payment and outgoing payment

### PR DESCRIPTION
**Pull request by raducristianpopa**
### Context

- fixes #786

### CODE REVIEW

File: packages/boutique/backend/migrations/20230824054747_add_products.js [hunk 1]
```diff
@@ -1,55 +1,61 @@
 const products = [
   {
+    id: '84af033c-00eb-4cde-b5ec-f18cf7adaea2',
     name: 'Luck',
     slug: 'luck',
     description:
       '&quot;I am a great believer in luck, and I find the harder I work, the more I have of it.&quot; - Thomas Jefferson',
-    price: 77.77,
+    price: 77.0,
```
Comment (raducristianpopa) [inline packages/boutique/backend/migrations/20230824054747_add_products.js:8]: Whole numbers until the off by `1n` issue is solved.

**Review by dragosp1011 — APPROVED** [review]
