### PR TITLE
fix: bug that less than 1 amount is not funding or withdrawing

### LINKED ISSUE #476: Fund/WIthdraw money < 1 amounts
Smaller amounts then 1 for funds and withdraw are not going through.
We should investigate.

### PR DESCRIPTION
**Pull request by rico191013**
### Context

- fixes #476

### CODE REVIEW

File: packages/wallet/frontend/src/lib/api/account.ts [hunk 1]
```diff
@@ -13,7 +13,7 @@ export const fundAccountSchema = z.object({
     .number({
       invalid_type_error: 'Please enter a valid amount'
     })
-    .min(1, { message: 'Please enter an amount' })
+    .min(0, { message: 'Please enter an amount' })
     .positive()
```
Comment (raducristianpopa) [inline packages/wallet/frontend/src/lib/api/account.ts:17]: [Zod numbers](https://zod.dev/?id=numbers).
```suggestion
    .nonnegative({ message: 'Please enter an amount' })
```

**Review by raducristianpopa — DISMISSED** [review]

File: packages/wallet/frontend/src/lib/api/account.ts [hunk 2]
```diff
@@ -13,8 +13,7 @@ export const fundAccountSchema = z.object({
     .number({
       invalid_type_error: 'Please enter a valid amount'
     })
-    .min(1, { message: 'Please enter an amount' })
-    .positive()
+    .nonnegative({ message: 'Please enter an amount' })
```
Comment (raducristianpopa) [inline packages/wallet/frontend/src/lib/api/account.ts:16]: My fault. It should be `positive` instead of `nonnegative`. `nonnegative` allows number that are >= 0.
```suggestion
    .positive({ message: 'Please enter an amount' })
```

**Review by beniaminmunteanu — APPROVED** [review]

**Review by raducristianpopa — APPROVED** [review]
