### PR TITLE
fix: Resend verification email

### LINKED ISSUE #1560: [BUG] Resend verification email
### Steps to reproduce

1. Create a new user with email address and receive verification email
2. Accidentaly delete all traces of your verification email
3. Try to log in, but EMail address is not verified error appears
4. No way to verify your email

### Expected result

There should be a way to resend verification email, when something happens with the original email. - EDGE CASE

### Actual result

There is no way of verifying an email again if something happens to the original verification email.

### Screenshots or videos

image

### Additional context

ToDO - 
- [ ] Add a Resend verification link when error message appears: Email address not verified.
- [ ] Make sure verification link is available for at least one day after email sent.
- [ ] Make sure Resend verification link is working and email is sent to the user again.

### Operating system

macOS

### Operating system version

_No response_

### Browsers

Chrome

### Browser version

_No response_

### PR DESCRIPTION
**Pull request by adrianboros**
### Context

- fixes #1560 

### Changes
 - add support to resend account validation email

### CODE REVIEW

File: packages/wallet/backend/src/app.ts [hunk 1]
```diff
@@ -171,6 +171,7 @@ export class App {
     router.get('/reset-password/:token/validate', userController.checkToken)
     router.post('/reset-password/:token', userController.resetPassword)
     router.post('/verify-email/:token', authController.verifyEmail)
+    router.post('/resend-verify-email', authController.resendVerifyEmail)
```
Comment (Tymmmy) [inline packages/wallet/backend/src/app.ts:174]: Token not needed here, as the other resend or reset password calls?

File: packages/wallet/backend/tests/auth/service.test.ts [hunk 2]
```diff
@@ -116,6 +116,30 @@ describe('Authentication Service', (): void => {
     })
   })
 
+  describe('ResendVerifyEmail', () => {
+    it('should return undefined if verification successfully sent', async () => {
```
Comment (Tymmmy) [inline packages/wallet/backend/tests/auth/service.test.ts:120]:
```suggestion
    it('should return undefined if verification email successfully sent', async () => {
```

**Review by Tymmmy — DISMISSED** [review]

**Review by lengyel-arpad85 — DISMISSED** [review]

**Review by Tymmmy — APPROVED** [review]

File: packages/wallet/backend/src/auth/service.ts [hunk 3]
```diff
@@ -54,21 +57,44 @@ export class AuthService implements IAuthService {
...
+    if (!user) {
+      throw new Unauthorized('Invalid account')
+    }
+    const token = getRandomToken()
+    await this.userService.resetVerifyEmailToken({
+      email,
+      verifyEmailToken: hashToken(token)
+    })
+
+    await this.emailService.sendVerifyEmail(email, token).catch((e) => {
```
Comment (dragosp1011) [inline packages/wallet/backend/src/auth/service.ts:75]: because the error is caught here, the response to frontend will be that email was successfully send
is this expected?

File: packages/wallet/backend/src/auth/service.ts [hunk 4]
```diff
@@ -54,21 +57,44 @@ export class AuthService implements IAuthService {
...
     // TODO: Prevent timing attacks
     if (!user) {
-      throw new Unauthorized('Invalid credentials')
+      throw new Unauthorized('Invalid credentials.')
     }
 
-    const isValid = await user.verifyPassword(args.password)
-    if (!isValid) {
-      throw new Unauthorized('Invalid credentials')
+    if (!user.isEmailVerified) {
```
Comment (dragosp1011) [inline packages/wallet/backend/src/auth/service.ts:91]: verifying the password first is the correct approach.
Telling the user that the email is not verified even if the password is incorrect increases security risks.

File: packages/wallet/frontend/src/lib/api/user.ts [hunk 5]
```diff
@@ -139,6 +139,9 @@ export const verifyIdentitySchema = z
 export const forgotPasswordSchema = z.object({
   email: z.string().email({ message: 'Email is required' })
 })
+export const resendVerificationEmailSchema = z.object({
```
Comment (dragosp1011) [inline packages/wallet/frontend/src/lib/api/user.ts:142]: move the schema to shared lib and use the same schema in both frontend and backend

Comment (dragosp1011) [reply packages/wallet/frontend/src/lib/api/user.ts:142]: as forgot password has the same schema use one generic schema for both cases

File: packages/wallet/frontend/src/lib/api/user.ts [hunk 6]
```diff
@@ -379,6 +393,19 @@ const createUserService = (): UserService => ({
     }
   },
 
+  async resendVerifyEmail(args) {
+    try {
+      const response = await httpClient
+        .post(`resend-verify-email/`, {
```
Comment (dragosp1011) [inline packages/wallet/frontend/src/lib/api/user.ts:399]: ``resend-verify-email/`` -> `'resend-verify-email'`

**Review by Tymmmy — DISMISSED** [review]

File: packages/wallet/backend/src/auth/service.ts [hunk 7]
```diff
@@ -54,21 +57,44 @@ export class AuthService implements IAuthService {
...
   }
 
+  public async resendVerifyEmail({
+    email
+  }: resendVerifyEmailArgs): Promise<void> {
+    const user = await this.userService.getByEmail(email)
+
+    // TODO: Prevent timing attacks
+    if (!user) {
+      throw new Unauthorized('Invalid account')
```
Comment (dragosp1011) [inline packages/wallet/backend/src/auth/service.ts:67]: I recommend that we don't send an error in this case and just return a success response
user should not be able to understand if an account exists or not to reduce security risks

File: packages/wallet/backend/src/user/service.ts [hunk 8]
```diff
@@ -214,6 +221,19 @@ export class UserService implements IUserService {
     })
   }
 
+  public async resetVerifyEmailToken(args: VerifyEmailArgs): Promise<void> {
+    const user = await this.getByEmail(args.email)
+
+    if (!user) {
+      throw new BadRequest('Invalid user')
```
Comment (dragosp1011) [inline packages/wallet/backend/src/user/service.ts:228]: sam here, should not be an error if user does not exist

**Review by dragosp1011 — APPROVED** [review]
